# Generated by Django 4.2.7 on 2024-01-02 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estresacademico',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estresacademico',
            name='emociones',
            field=models.CharField(max_length=255),
        ),
    ]