# Generated by Django 4.2.7 on 2024-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_estresacademico_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estresacademico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
