# Generated by Django 4.2.7 on 2024-01-02 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_icon_userprofile_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='image',
        ),
        migrations.AddField(
            model_name='icon',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 1, 2, 23, 54, 55, 527470, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
