# Generated by Django 4.2.7 on 2024-01-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_icon_image_icon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purchased_products',
            field=models.ManyToManyField(to='App.product'),
        ),
    ]
