# Generated by Django 4.2.7 on 2024-01-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_icon_image_alter_userprofile_purchased_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
