# Generated by Django 4.2.7 on 2024-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_icon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='gif',
            field=models.FileField(default='default.gif', upload_to='product_gifs/'),
        ),
    ]
