# Generated by Django 4.2.7 on 2024-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_avatar_userprofile_selected_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('producto', 'Producto'), ('cabeza', 'Cabeza'), ('torso', 'Torso'), ('pierna', 'Pierna'), ('pie', 'Pie'), ('background', 'Background')], default='producto', max_length=20),
        ),
    ]
